### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/melissadelbosque.com#11]
- [x] Update font files

In the site's files:

- [x] (config.toml) change `baseurl` to whatever the final domain is, including the www and https protocol (e.g. https://www.example.com)
- [x] (netlify.toml) change the HUGO_ENV in the production env to "production"

---

At domain registrar or wherever the NS records are managed, update the following:

- [x] CNAME: "www" to "site_name.netlify.com"
- [x] A: @ to 104.198.14.52

site_name: melissa-del-bosque (e.g. melissa-del-bosque.netlify.com)

For more information, see: https://www.netlify.com/docs/custom-domains/#dns-configuration

---

Once the domain is set, (Netlify: /site settings/domain management/)
- [x] turn off site control if there was a password set.
- [x] change the domain name in the Netlify control panel (../custom domain).
- [x] provision Lets Encrypt certificate (/domain).
- [x] force TLS connecttions

---
- [x] Add headers info to config (placeholder for more info on this)
- [x] Review headers for proper data
- [ ] Review content security policy items.
- [x] Create/Retreive tracking ID and to `googleAnalytics` in config

---
Test setttings:
- [x] View the live production site and make sure the word `production` shows up as a body class and make sure open graph and other social tags are rendering.
- [x] View a sample page on Facebook's object debug https://developers.facebook.com/tools/debug/og/object/

**Comment by AdamChlan** [comment]
Just noting that these settings have been put into place. Will keep an eye on the site today to see if it resolves.

**Comment by budparr** [comment]
Thanks. I owe you more checklist stuff. If you can, think through anything you do when launching a site and list it out as if you were giving the list to a newbie.

**Comment by budparr** [comment]
@AdamChlan I updated my original post with next steps. For items to do with site files, you can reference this issue in your commit. If you can check off items that I've created, please do so.
